name: TAO extension CI
description: Executes a CI pipeline on a TAO extension
inputs:
  extension-name-config:
    description: TAO extension name configuration field
    required: true
    default: tao-extension-name
  test-suites-path:
    description: Relative path to the test suits
    required: true
    default: test/unit
runs:
  using: composite
  steps:
    - name: Set default phpunit configuration if it doesn't exist
      shell: bash
      run: mv -n "${{ github.action_path }}/phpunit.xml" .
    - name: Fetch extension's name
      id: configuration
      shell: bash
      run: echo ::set-output name=extension-name::$(composer config "extra.${{ inputs.extension-name-config }}" --no-interaction --no-plugins)
    - name: Determine bootstrap path
      id: bootstrap
      shell: bash
      run: echo ::set-output name=path::$([ "${{ steps.configuration.outputs.extension-name }}" = generis ] && echo test/bootstrap.php || echo generis/test/bootstrap.php)
    - name: Validate dependencies' list
      shell: bash
      run: composer validate --no-interaction --no-plugins
    - name: Disable NPM plugin
      shell: bash
      run: composer config allow-plugins.oat-sa/composer-npm-bridge false --no-interaction --no-plugins
    - name: Allow TAO extension installer plugin
      shell: bash
      run: composer config allow-plugins.oat-sa/oatbox-extension-installer true --no-interaction --no-plugins
    - name: Install phpunit
      shell: bash
      run: composer require "phpunit/phpunit:*" --dev -W --no-interaction
    - name: Convert phpunit configuration
      shell: bash
      run: vendor/bin/phpunit --migrate-configuration || true
    - name: Execute Unit tests
      shell: bash
      run: php -dxdebug.mode=coverage vendor/bin/phpunit --bootstrap "${{ steps.bootstrap.outputs.path }}" --coverage-clover coverage.xml "${{ inputs.test-suites-path }}"
    - name: Push coverage report
      shell: bash
      run: bash <(curl -s https://codecov.io/bash)
