name: TAO extension CI
description: Executes a CI pipeline on a TAO extension
inputs:
  php:
    description: PHP version to power the CI
    required: true
  coverage:
    description: Boolean flag controlling whether or not the pipeline will generate a code coverage report
    required: false
    type: boolean
    default: false
  extension-name-config:
    description: TAO extension name configuration field
    required: false
    default: tao-extension-name
  test-suites-path:
    description: Relative path to the test suits
    required: false
    default: test/unit
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php }}
    - name: Set default phpunit configuration if it doesn't exist
      shell: bash
      run: mv -n "${{ github.action_path }}/phpunit.xml" .
    - name: Fetch extension's name
      id: configuration
      shell: bash
      run: echo ::set-output name=extension-name::$(composer config "extra.${{ inputs.extension-name-config }}" --no-interaction --no-plugins)
    - name: Determine bootstrap path
      id: bootstrap
      shell: bash
      run: echo ::set-output name=path::$([ "${{ steps.configuration.outputs.extension-name }}" = generis ] && echo test/bootstrap.php || echo generis/test/bootstrap.php)
    - name: Validate dependencies' list
      shell: bash
      run: composer validate --no-interaction --no-plugins
    - name: Disable NPM plugin
      shell: bash
      run: composer config allow-plugins.oat-sa/composer-npm-bridge false --no-interaction --no-plugins
    - name: Allow TAO extension installer plugin
      shell: bash
      run: composer config allow-plugins.oat-sa/oatbox-extension-installer true --no-interaction --no-plugins
    - name: Install phpunit
      shell: bash
      run: composer require "phpunit/phpunit:*" --dev -W --no-interaction
    - name: Convert phpunit configuration
      shell: bash
      run: vendor/bin/phpunit --migrate-configuration || true
    - name: Execute Unit tests
      shell: bash
      run: vendor/bin/phpunit --bootstrap "${{ steps.bootstrap.outputs.path }}"${{ inputs.coverage && ' --coverage-clover coverage.xml' }} "${{ inputs.test-suites-path }}"
    - uses: codecov/codecov-action@v3
      if: ${{ inputs.coverage }}
